### ISSUE TITLE
Publish on Accrescent store

### ISSUE THREAD

**Issue by shuvashish76** [CryZo/PaintballNotificator#10]
[Accrescent](https://github.com/accrescent/accrescent) is an alternative android app store.

See their guide: https://accrescent.app/docs/guide/getting-started/

**Comment by Chaser-0** [comment]
Thanks for reaching out to me! I'll give it try. If you're interested in getting this app from other sources than Google Play, you may like to hear, that this app will be available on fdroid soon

**Comment by shuvashish76** [comment]
The project is still in alpha phase, you can contact them on [Matrix](https://matrix.to/#/#accrescent:matrix.org), if you've some queries.

**Comment by Chaser-0** [comment]
I don't think the effort would be worth it. So I'll close this for now.
